// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0b6zpltLYI5a6hEyNVBiONUKvs205VJE',
    appId: '1:688703949293:web:e6662cc7fff7f78b4cbfe4',
    messagingSenderId: '688703949293',
    projectId: 'fridge-manager-ddbd6',
    authDomain: 'fridge-manager-ddbd6.firebaseapp.com',
    storageBucket: 'fridge-manager-ddbd6.appspot.com',
    measurementId: 'G-2YP9DB9GSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-21C8erMqudlzBKRmgAYcVbjPX0Enyw8',
    appId: '1:688703949293:android:85c206441e452a624cbfe4',
    messagingSenderId: '688703949293',
    projectId: 'fridge-manager-ddbd6',
    storageBucket: 'fridge-manager-ddbd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgN-b1shZfXRYxXD-m4xs5X1zEHW5ctVk',
    appId: '1:688703949293:ios:dba693986637522c4cbfe4',
    messagingSenderId: '688703949293',
    projectId: 'fridge-manager-ddbd6',
    storageBucket: 'fridge-manager-ddbd6.appspot.com',
    iosBundleId: 'com.example.fridgeManager',
  );
}
